version: '3'

services:
  php:
    build: ./php
    volumes: 
      - ./php:/var/www/html
    depends_on:
      - mariadb
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./php:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - php
      - mariadb
    networks:
      - app-network
  
  mariadb:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
    networks:
      - app-network
    ports:
      - 3306:3306

networks:
  app-network: